### PR TITLE
Repo maintenance and expose schema

### PR DESCRIPTION
**Pull request by cjihrig**
Three commits:

- Update dependencies (only `code`).
- Add Node 7 to the Travis file.
- Attach the schema to the validation middleware.

### CODE REVIEW

**Comment by cjihrig** [comment]
Yep, a patch sounds good to me. I'll do it if you feel like giving me npm publish rights.

**Comment by MuhamadOmr** [comment]
@arb i have a question here
why was _schema added on the middleware ?

**Comment by arb** [comment]
So it could, technically, be consumed by another library for documentation generation. It is not documented or public so I wouldn't rely on it unless you're sure you really need it. It can also break at any time.

**Comment by MuhamadOmr** [comment]
@arb thank you for the clarification

**Pull request merged**
